### ISSUE TITLE
RichTextBox HTML Support Article Malformed

### ISSUE THREAD

**Issue by LanceMcCarthy** [telerik/xaml-docs#1489] opened 2018-12-18 18:35 UTC
When loading [this HTML Support article](https://docs.telerik.com/devtools/wpf/controls/radrichtextbox/import-export/html/features-html-support), the page has overlaying HTML tags in the page. This occurs in at least Chrome and Firefox.

![image](https://user-images.githubusercontent.com/3520532/50174986-af0c1f00-02c9-11e9-8eff-229c8e53b973.png)

**Comment by imtodor** [comment] 2018-12-19 09:04
Hey @LanceMcCarthy , the issue is fixed with this commit - https://github.com/telerik/docs-seed/commit/a81b9c7f5828fd97780be3c843cec0f16eb2b8c7 . We are promoting the new WPF docs to LIVE environment, so the messy content will be gone in a few minutes :)

Thanks to you and @TanyaDimitrova for reporting this.

**Closed by imtodor** 2018-12-19 09:04 UTC
